package problems1to9;

//Question -----------------------------------------------------------------------------------------------------------------------
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//---------- -----------------------------------------------------------------------------------------------------------------------
//Solution correct

public class Problem2 {


	public static void main(String[]args){
		 int fib1 = 1;
		 int fib2 = 2; 
		 int sum = 0;
		 
		 // while both fib numbers are smaller than 4 million
		 // go through them and if they are even add them to 
		 // the sum 
		 while(fib1 < 4*1E6 && fib2 < 4*1E6){
			 if(fib1 % 2 == 0){
				 sum += fib1;
			 }
			 if(fib2 % 2 == 0){
				 sum += fib2; 
			 }
			 fib1 += fib2;
			 fib2 += fib1;
		
			
		 }
		// print out the answer 
		System.out.println(sum);
	}
}
