package problems20to29;

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

//Question -----------------------------------------------------------------------------------------------------------------------
// Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
//
// 22=4, 23=8, 24=16, 25=32
// 32=9, 33=27, 34=81, 35=243
// 42=16, 43=64, 44=256, 45=1024
// 52=25, 53=125, 54=625, 55=3125
// If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
//
// 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
//
// How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
//---------- -----------------------------------------------------------------------------------------------------------------------
//Solution correct 

public class Problem29 {

	public static void main(String[] args) {
		Set<BigInteger> numbers = new HashSet<BigInteger>();		// using a set to avoid duplicates 
		
		// Go through all the terms adding them to the set, using
		// BigIntegers to avoid overflow
		for(int a = 2; a <= 100; a++) {
			for(int b = 2; b<= 100; b++) {
				BigInteger tempInteger = BigInteger.valueOf(a);	
				tempInteger = tempInteger.pow(b);	
				numbers.add(tempInteger);
			}									
		}
		// Print out the answer 
		System.out.println(numbers.size());
	}
}
